---
- name: Install sshd
  become: True
  apt:
    name: openssh-server
    state: present

- name: Configure sshd
  become: True
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd
